version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6479:6479"
    volumes:
      - data-volume:/usr/cache
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    ports:
      - "28017:28017"
    volumes:
      - data-volume:/usr/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/usr/docker-entrypoint-initdb.d/mongo-init.js:ro
  marine-unit-monitoring:
    container_name: marine-unit-monitoring
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
      - redis
    depends_on:
      - redis
      - mongodb
volumes:
  data-volume: