version: '3'
services:
  redis:
    container_name: redis
    build: .
    ports:
      - "6379:6379"
    volumes:
      - data-volume:/usr/cache
  mongodb:
    container_name: mongodb
    build: .
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/usr/db
  marine-unit-monitoring:
    container_name: marine-unit-monitoring
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb
volumes:
  data-volume: