version: '3.1'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6479:6479"
    volumes:
      - cache-volume:/usr/cache
    networks:
      - marine-unit-monitoring-network
  mongodb1:
    container_name: mongodb1
    hostname: mongodb1
    image: mongo:latest
    command: --replSet marine-unit-monitoring-db-rs --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    volumes:
      - db-volume1:/usr/db
      - mongo-init:/usr/docker-entrypoint-init.d/mongo-init.js
      - mongo-rs-init:/usr/docker-entrypoint-init.d/mongo-rs-init.sh
    networks:
      - marine-unit-monitoring-network
    # todo permission denied for mongo-rs-init.sh - mongo-rs-init.sh is a directory in container file sys
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Granting permissions for mongo-rs-init.sh"
        chmod +x /usr/docker-entrypoint-init.d/mongo-rs-init.sh
        /usr/docker-entrypoint-init.d/mongo-rs-init.sh
  mongodb2:
    container_name: mongodb2
    hostname: mongodb2
    image: mongo:latest
    command: [ "--replSet", "marine-unit-monitoring-db-rs", "--bind_ip_all", "--port", "27018" ]
    ports:
      - "27027:27017"
    volumes:
      - db-volume2:/usr/db
      - mongo-init:/usr/docker-entrypoint-init.d/mongo-init.js
    networks:
      - marine-unit-monitoring-network
  mongodb3:
    container_name: mongodb3
    hostname: mongodb3
    image: mongo:latest
    command: [ "--replSet", "marine-unit-monitoring-db-rs", "--bind_ip_all", "--port", "27019" ]
    ports:
      - "27037:27017"
    volumes:
      - db-volume3:/usr/db
      - mongo-init:/usr/docker-entrypoint-init.d/mongo-init.js
    networks:
      - marine-unit-monitoring-network
  marine-unit-monitoring:
    container_name: marine-unit-monitoring
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - marine-unit-monitoring-network
volumes:
  cache-volume:
  db-volume1:
  db-volume2:
  db-volume3:
  mongo-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-entrypoint-init.d/
  mongo-rs-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-entrypoint-init.d/
networks:
  marine-unit-monitoring-network:
