version: '3.8'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6479:6479"
    volumes:
      - cache-volume:/usr/cache
    networks:
      - marine-unit-monitoring-network
  mongodb-primary:
    container_name: mongodb-primary
    hostname: mongodb-primary
    image: mongo:latest
    command:
      - bin/sh
      - -c
      - |
        /usr/db-init/mongo-keyfile-init.sh
        mongod --replSet marine-unit-monitoring-db-rs --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - db-volume1:/usr/db
      - mongo-init:/usr/db-init/
    networks:
      - marine-unit-monitoring-network
    depends_on:
      - mongodb2
      - mongodb3
  mongodb2:
    container_name: mongodb2
    hostname: mongodb2
    image: mongo:latest
    command:
      - bin/sh
      - -c
      - |
        /usr/db-init/mongo-keyfile-init.sh
        mongod --replSet marine-unit-monitoring-db-rs --bind_ip_all
    ports:
      - "27027:27017"
    volumes:
      - db-volume2:/usr/db
      - mongo-init:/usr/db-init/
    networks:
      - marine-unit-monitoring-network
  mongodb3:
    container_name: mongodb3
    hostname: mongodb3
    image: mongo:latest
    command:
      - bin/sh
      - -c
      - |
        /usr/db-init/mongo-keyfile-init.sh
        mongod --replSet marine-unit-monitoring-db-rs --bind_ip_all
    ports:
      - "27037:27017"
    volumes:
      - db-volume3:/usr/db
      - mongo-init:/usr/db-init/
    networks:
      - marine-unit-monitoring-network
  marine-unit-monitoring:
    container_name: marine-unit-monitoring
    build:
      context: .
      dockerfile: ./Dockerfile
    image: marine-unit-monitoring:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - redis
      - mongodb-primary
      - mongodb2
      - mongodb3
    networks:
      - marine-unit-monitoring-network
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
volumes:
  cache-volume:
  db-volume1:
  db-volume2:
  db-volume3:
  mongo-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-deploy/db-init/
networks:
  marine-unit-monitoring-network:
