spring:
  data:
    mongodb:
      database: marine_unit_monitoring
      uri: mongodb://mongodb1,mongodb2,mongodb3/${spring.data.mongodb.database}?replicaSet=marine-unit-monitoring-db-rs
    redis:
      host: redis
      port: 6379