spring:
  data:
    mongodb:
      database: marine_unit_monitoring
      uri: mongodb://mongodb-primary,mongodb2,mongodb3/${spring.data.mongodb.database}?replicaSet=marine-unit-monitoring-db-rs
    redis:
      host: redis
      port: 6379

project-properties:
  app:
    frontend-integration:
      base-url: http://localhost:3306
      endpoint-paths:
        email-verification: /verify-email
  oauth2:
    resource-server:
      multi-providers-jws-key-selector:
        providers:
          - issuer-uri: https://accounts.google.com
            jwks-uri: https://www.googleapis.com/oauth2/v3/certs
          - issuer-uri: https://www.facebook.com
            jwks-uri: https://limited.facebook.com/.well-known/oauth/openid/jwks/
  external-apis:
    ais-api:
      result-limit: 5
  scheduling-delays:
    in-ms:
      ship-tracking:
        saving: 300000 # 5 min
      jwt-blacklist:
        clearing: 86400000 # 24h
      email-verification:
        clearing: 86400000 # 24h
  expiration-times:
    jwt:
      refresh-token: 86400000 # ms - 24h
      access-token: 3600000 # ms - 1h
    verification:
      email-token: 24 # hours
  security:
    token:
      bearer:
        type: Bearer
        regex: ^Bearer\s+(\S+)
    jwt:
      issuer: marine-unit-monitoring