spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: marine_unit_monitoring
      uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}
    redis:
      host: localhost
      port: 6379