server:
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: docker
  cache:
    type: redis
  config:
    import: classpath:secrets.yaml
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    org.springframework.security: debug
    org.springframework.data.mongodb: debug
    org.springframework.data.redis: debug