spring:
  profiles:
    active: docker # todo mvn profiles
  cache:
    type: redis
  config:
    import: classpath:secrets.yaml

logging:
  level:
    web: debug
    org.springframework.data.mongodb: debug
    org.springframework.data.redis: debug