spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: marine_unit_monitoring
      uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}
    redis:
      host: localhost
      port: 6379

secrets:
  ais-api:
    auth:
      url: https://id.barentswatch.no/connect/token
      client-id: bartek21122006@gmail.com:bartek21122006@gmail.com
      scope: ais
      client-secret: Bartek2006bartek
      grant-type: client_credentials
    latest-ais-url: https://live.ais.barentswatch.no/v1/latest/combined?modelType=Full&modelFormat=Geojson
    latest-ais-bymmsi-url: https://live.ais.barentswatch.no/v1/latest/combined
  geocode-api:
    api-key: TQeBKTVelWEdjylTOY9K6XAXapgtQ3CxZa830ZToHh8
    result-limit: 5