spring:
  profiles:
    active: local
  cache:
    type: redis
  config:
    import: file:./src/main/resources/secrets.yaml

logging:
  level:
    web: debug
    org.springframework.data.mongodb: debug
    org.springframework.data.redis: debug