spring:
  data:
    mongodb:
      database: marine_unit_monitoring
      uri: mongodb://mongodb-primary,mongodb2,mongodb3/${spring.data.mongodb.database}?replicaSet=marine-unit-monitoring-db-rs
    redis:
      host: redis
      port: 6379
vars:
  api:
    ais:
      result-limit: 5